/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 29
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 31
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_source_file_token1 = 1,
  aux_sym_content_token1 = 2,
  aux_sym_content_token2 = 3,
  aux_sym_content_token3 = 4,
  aux_sym_content_token4 = 5,
  aux_sym_content_token5 = 6,
  aux_sym_content_token6 = 7,
  aux_sym_content_token7 = 8,
  aux_sym_content_token8 = 9,
  aux_sym_content_token9 = 10,
  anon_sym_BANG_BANGimport_COLON = 11,
  anon_sym_SPACE = 12,
  anon_sym_DQUOTE = 13,
  aux_sym_quoted_module_token1 = 14,
  sym_text = 15,
  sym_code_open = 16,
  sym_code_close = 17,
  anon_sym_COLON = 18,
  aux_sym_code_function_token1 = 19,
  aux_sym_raw_text_token1 = 20,
  aux_sym_raw_text_token2 = 21,
  sym_source_file = 22,
  sym_content = 23,
  sym_import_directive = 24,
  sym_quoted_module = 25,
  sym_code = 26,
  sym_code_function = 27,
  sym_raw_text = 28,
  aux_sym_content_repeat1 = 29,
  aux_sym_import_directive_repeat1 = 30,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_source_file_token1] = "source_file_token1",
  [aux_sym_content_token1] = "content_token1",
  [aux_sym_content_token2] = "content_token2",
  [aux_sym_content_token3] = "content_token3",
  [aux_sym_content_token4] = "content_token4",
  [aux_sym_content_token5] = "content_token5",
  [aux_sym_content_token6] = "content_token6",
  [aux_sym_content_token7] = "content_token7",
  [aux_sym_content_token8] = "content_token8",
  [aux_sym_content_token9] = "content_token9",
  [anon_sym_BANG_BANGimport_COLON] = "!!import:",
  [anon_sym_SPACE] = " ",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_module_token1] = "quoted_module_token1",
  [sym_text] = "text",
  [sym_code_open] = "code_open",
  [sym_code_close] = "code_close",
  [anon_sym_COLON] = ":",
  [aux_sym_code_function_token1] = "code_function_token1",
  [aux_sym_raw_text_token1] = "raw_text_token1",
  [aux_sym_raw_text_token2] = "raw_text_token2",
  [sym_source_file] = "source_file",
  [sym_content] = "content",
  [sym_import_directive] = "import_directive",
  [sym_quoted_module] = "quoted_module",
  [sym_code] = "code",
  [sym_code_function] = "code_function",
  [sym_raw_text] = "raw_text",
  [aux_sym_content_repeat1] = "content_repeat1",
  [aux_sym_import_directive_repeat1] = "import_directive_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_source_file_token1] = aux_sym_source_file_token1,
  [aux_sym_content_token1] = aux_sym_content_token1,
  [aux_sym_content_token2] = aux_sym_content_token2,
  [aux_sym_content_token3] = aux_sym_content_token3,
  [aux_sym_content_token4] = aux_sym_content_token4,
  [aux_sym_content_token5] = aux_sym_content_token5,
  [aux_sym_content_token6] = aux_sym_content_token6,
  [aux_sym_content_token7] = aux_sym_content_token7,
  [aux_sym_content_token8] = aux_sym_content_token8,
  [aux_sym_content_token9] = aux_sym_content_token9,
  [anon_sym_BANG_BANGimport_COLON] = anon_sym_BANG_BANGimport_COLON,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_module_token1] = aux_sym_quoted_module_token1,
  [sym_text] = sym_text,
  [sym_code_open] = sym_code_open,
  [sym_code_close] = sym_code_close,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_code_function_token1] = aux_sym_code_function_token1,
  [aux_sym_raw_text_token1] = aux_sym_raw_text_token1,
  [aux_sym_raw_text_token2] = aux_sym_raw_text_token2,
  [sym_source_file] = sym_source_file,
  [sym_content] = sym_content,
  [sym_import_directive] = sym_import_directive,
  [sym_quoted_module] = sym_quoted_module,
  [sym_code] = sym_code,
  [sym_code_function] = sym_code_function,
  [sym_raw_text] = sym_raw_text,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
  [aux_sym_import_directive_repeat1] = aux_sym_import_directive_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_token5] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_token6] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_token7] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_token8] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_token9] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BANG_BANGimport_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_module_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_code_open] = {
    .visible = true,
    .named = true,
  },
  [sym_code_close] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_code_function_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_raw_text_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_raw_text_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_import_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_module] = {
    .visible = true,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_code_function] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '"') ADVANCE(35);
      if (lookahead == ':') ADVANCE(42);
      if (lookahead == '<') ADVANCE(14);
      if (lookahead == '|') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(21);
      if (lookahead == ' ') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '!') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 4:
      if (lookahead == '!') ADVANCE(8);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(33);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(41);
      END_STATE();
    case 8:
      if (lookahead == 'i') ADVANCE(9);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 9:
      if (lookahead == 'm') ADVANCE(11);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(12);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 11:
      if (lookahead == 'p') ADVANCE(10);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(13);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(6);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 14:
      if (lookahead == '|') ADVANCE(40);
      END_STATE();
    case 15:
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 16:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(37);
      END_STATE();
    case 17:
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(47);
      END_STATE();
    case 18:
      if (lookahead != 0 &&
          lookahead != '|') ADVANCE(39);
      END_STATE();
    case 19:
      if (eof) ADVANCE(20);
      if (lookahead == '<') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_source_file_token1);
      if (lookahead == '\n') ADVANCE(21);
      if (lookahead == ' ') ADVANCE(34);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_source_file_token1);
      if (lookahead == '\n') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_content_token1);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '!') ADVANCE(23);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_content_token2);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_content_token3);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_content_token4);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_content_token5);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_content_token6);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_content_token7);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_content_token8);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_content_token9);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_BANG_BANGimport_COLON);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == '\n') ADVANCE(21);
      if (lookahead == ' ') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_quoted_module_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_quoted_module_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '<') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '<') ADVANCE(18);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_code_open);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_code_close);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_code_function_token1);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_raw_text_token1);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_raw_text_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(44);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_raw_text_token2);
      if (lookahead == '|') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_raw_text_token2);
      if (lookahead == '|') ADVANCE(17);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 3},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 19},
  [4] = {.lex_state = 19},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 19},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 19},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 19},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 16},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 46},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_content_token2] = ACTIONS(1),
    [aux_sym_content_token3] = ACTIONS(1),
    [aux_sym_content_token4] = ACTIONS(1),
    [aux_sym_content_token5] = ACTIONS(1),
    [aux_sym_content_token6] = ACTIONS(1),
    [aux_sym_content_token7] = ACTIONS(1),
    [aux_sym_content_token8] = ACTIONS(1),
    [aux_sym_content_token9] = ACTIONS(1),
    [anon_sym_BANG_BANGimport_COLON] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_code_open] = ACTIONS(1),
    [sym_code_close] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_code_function_token1] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(17),
    [sym_content] = STATE(20),
    [sym_import_directive] = STATE(19),
    [aux_sym_content_token1] = ACTIONS(3),
    [aux_sym_content_token2] = ACTIONS(5),
    [aux_sym_content_token3] = ACTIONS(5),
    [aux_sym_content_token4] = ACTIONS(5),
    [aux_sym_content_token5] = ACTIONS(5),
    [aux_sym_content_token6] = ACTIONS(5),
    [aux_sym_content_token7] = ACTIONS(5),
    [aux_sym_content_token8] = ACTIONS(5),
    [aux_sym_content_token9] = ACTIONS(5),
    [anon_sym_BANG_BANGimport_COLON] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      aux_sym_content_token1,
    STATE(25), 1,
      sym_content,
    ACTIONS(5), 8,
      aux_sym_content_token2,
      aux_sym_content_token3,
      aux_sym_content_token4,
      aux_sym_content_token5,
      aux_sym_content_token6,
      aux_sym_content_token7,
      aux_sym_content_token8,
      aux_sym_content_token9,
  [17] = 4,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      sym_text,
    ACTIONS(13), 1,
      sym_code_open,
    STATE(4), 2,
      sym_code,
      aux_sym_content_repeat1,
  [31] = 4,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      sym_text,
    ACTIONS(20), 1,
      sym_code_open,
    STATE(4), 2,
      sym_code,
      aux_sym_content_repeat1,
  [45] = 4,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(25), 1,
      aux_sym_raw_text_token1,
    STATE(15), 1,
      sym_code_function,
    STATE(28), 1,
      sym_raw_text,
  [58] = 3,
    ACTIONS(13), 1,
      sym_code_open,
    ACTIONS(27), 1,
      sym_text,
    STATE(3), 2,
      sym_code,
      aux_sym_content_repeat1,
  [69] = 3,
    ACTIONS(29), 1,
      aux_sym_source_file_token1,
    ACTIONS(31), 1,
      anon_sym_SPACE,
    STATE(8), 1,
      aux_sym_import_directive_repeat1,
  [79] = 3,
    ACTIONS(31), 1,
      anon_sym_SPACE,
    ACTIONS(33), 1,
      aux_sym_source_file_token1,
    STATE(10), 1,
      aux_sym_import_directive_repeat1,
  [89] = 2,
    ACTIONS(37), 1,
      sym_code_open,
    ACTIONS(35), 2,
      ts_builtin_sym_end,
      sym_text,
  [97] = 3,
    ACTIONS(39), 1,
      aux_sym_source_file_token1,
    ACTIONS(41), 1,
      anon_sym_SPACE,
    STATE(10), 1,
      aux_sym_import_directive_repeat1,
  [107] = 2,
    ACTIONS(46), 1,
      sym_code_open,
    ACTIONS(44), 2,
      ts_builtin_sym_end,
      sym_text,
  [115] = 2,
    ACTIONS(48), 1,
      anon_sym_DQUOTE,
    STATE(7), 1,
      sym_quoted_module,
  [122] = 1,
    ACTIONS(50), 2,
      aux_sym_source_file_token1,
      anon_sym_SPACE,
  [127] = 2,
    ACTIONS(48), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      sym_quoted_module,
  [134] = 2,
    ACTIONS(25), 1,
      aux_sym_raw_text_token1,
    STATE(26), 1,
      sym_raw_text,
  [141] = 1,
    ACTIONS(39), 2,
      aux_sym_source_file_token1,
      anon_sym_SPACE,
  [146] = 1,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
  [150] = 1,
    ACTIONS(54), 1,
      aux_sym_quoted_module_token1,
  [154] = 1,
    ACTIONS(56), 1,
      aux_sym_source_file_token1,
  [158] = 1,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
  [162] = 1,
    ACTIONS(60), 1,
      aux_sym_code_function_token1,
  [166] = 1,
    ACTIONS(62), 1,
      aux_sym_raw_text_token2,
  [170] = 1,
    ACTIONS(64), 1,
      aux_sym_raw_text_token1,
  [174] = 1,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
  [178] = 1,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
  [182] = 1,
    ACTIONS(70), 1,
      sym_code_close,
  [186] = 1,
    ACTIONS(72), 1,
      sym_code_close,
  [190] = 1,
    ACTIONS(74), 1,
      sym_code_close,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 17,
  [SMALL_STATE(4)] = 31,
  [SMALL_STATE(5)] = 45,
  [SMALL_STATE(6)] = 58,
  [SMALL_STATE(7)] = 69,
  [SMALL_STATE(8)] = 79,
  [SMALL_STATE(9)] = 89,
  [SMALL_STATE(10)] = 97,
  [SMALL_STATE(11)] = 107,
  [SMALL_STATE(12)] = 115,
  [SMALL_STATE(13)] = 122,
  [SMALL_STATE(14)] = 127,
  [SMALL_STATE(15)] = 134,
  [SMALL_STATE(16)] = 141,
  [SMALL_STATE(17)] = 146,
  [SMALL_STATE(18)] = 150,
  [SMALL_STATE(19)] = 154,
  [SMALL_STATE(20)] = 158,
  [SMALL_STATE(21)] = 162,
  [SMALL_STATE(22)] = 166,
  [SMALL_STATE(23)] = 170,
  [SMALL_STATE(24)] = 174,
  [SMALL_STATE(25)] = 178,
  [SMALL_STATE(26)] = 182,
  [SMALL_STATE(27)] = 186,
  [SMALL_STATE(28)] = 190,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 2, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_directive, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_directive, 3, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code, 3, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_import_directive_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_import_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code, 4, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code, 4, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_module, 3, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_function, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_text, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tet(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "tet",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
